name: Nick
main: Nick\Main
authors: [BoyIsDino,XFuryMCPE]
api: [2.0.0]
version: 1.0.1
commands:
 nick:
  description: Gives the sender a Nickname
  permission: nick

permissions:
 nick:
  description: Permission to allow setting nicknames
  default: op
